Models/Enrollment.cs
using System.ComponentModel.DataAnnotations;

namespace School_Management_System_Application.Models
{
    public class Enrollment
    {
        public long enrollmentId { get; set; }

        [Display(Name = "Course")]
        public int courseId { get; set; }
        [Display(Name = "Course")]
        public Course? course { get; set; }

        [Display(Name = "Student")]
        public long studentId { get; set; }
        [Display(Name = "Student")]
        public Student? student { get; set; }

        [Display(Name = "Semester")]
        public string? semester { get; set; }

        [Display(Name = "Year")]
        public int? year { get; set; }

        [Display(Name = "Grade")]
        public int? grade { get; set; }

        [StringLength(255, MinimumLength = 3)]
        [Display(Name = "Seminal Url")]
        public string? seminalUrl { get; set; }

        [StringLength(255, MinimumLength = 3)]
        [Display(Name = "Project Url")]
        public string? projectUrl { get; set; }

        [Display(Name = "Exam Points")]
        public int? examPoints { get; set; }

        [Display(Name = "Seminal Points")]
        public int? seminalPoints { get; set; }

        [Display(Name = "Project Points")]
        public int? projectPoints { get; set; }

        [Display(Name = "Additional Points")]
        public int? additionalPoints { get; set; }

        [Display(Name = "Finish Date")]
        [DataType(DataType.Date)]
        public DateTime? finishDate { get; set; }

        [Display(Name = "Total Points")]
        public int totalPoints
        {
            get
            {
                if (examPoints == null)
                    examPoints = 0;
                if (seminalPoints == null)
                    seminalPoints = 0;
                if (projectPoints == null)
                    projectPoints = 0;
                if (additionalPoints == null)
                    additionalPoints = 0;
                int points = (int)(examPoints + seminalPoints + projectPoints + additionalPoints);
                return (int)points;
            }
        }
    }
}

ViewModels/EditAsStudentViewModel.cs
using School_Management_System_Application.Models;
using System.ComponentModel.DataAnnotations;

namespace School_Management_System_Application.ViewModels
{
    public class EditAsStudentViewModel
    {
        public Enrollment enrollment { get; set; }

        [Display(Name = "Seminal File")]
        public IFormFile? seminalUrlFile { get; set; }

        public string? seminalUrlName { get; set; }
    }
}

Controllers/EnrollmentsController.cs
#nullable disable
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using School_Management_System_Application.Data;
using School_Management_System_Application.Models;
using School_Management_System_Application.ViewModels;
using IWebHostEnvironment = Microsoft.AspNetCore.Hosting.IWebHostEnvironment;

namespace School_Management_System_Application.Controllers
{
    public class EnrollmentsController : Controller
    {
        private readonly School_Management_System_ApplicationContext _context;
        private readonly IWebHostEnvironment webHostEnvironment;

        public EnrollmentsController(School_Management_System_ApplicationContext context)
        {
            _context = context;
        }

        // GET: Enrollments
        [Authorize(Roles = "Admin")]
        public async Task<IActionResult> Index()
        {
            var school_Management_System_ApplicationContext = _context.Enrollment.Include(e => e.course).Include(e => e.student);
            return View(await school_Management_System_ApplicationContext.ToListAsync());
        }

        // GET: Enrollments/Details/5
        [Authorize]
        public async Task<IActionResult> Details(long? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var enrollment = await _context.Enrollment
                .Include(e => e.course)
                .Include(e => e.student)
                .FirstOrDefaultAsync(m => m.enrollmentId == id);
            if (enrollment == null)
            {
                return NotFound();
            }

            return View(enrollment);
        }

        // GET: Enrollments/Create
        [Authorize(Roles = "Admin")]
        public IActionResult Create()
        {
            ViewData["courseId"] = new SelectList(_context.Course, "courseId", "title");
            ViewData["studentId"] = new SelectList(_context.Student, "Id", "fullName");
            return View();
        }

        // POST: Enrollments/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        [Authorize(Roles = "Admin")]
        public async Task<IActionResult> Create([Bind("enrollmentId,courseId,studentId,semester,year,grade,seminalUrl,projectUrl,examPoints,seminalPoints,projectPoints,additionalPoints,finishDate,student,course")] Enrollment enrollment)
        {
            if (ModelState.IsValid)
            {
                _context.Add(enrollment);
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
            }
            ViewData["courseId"] = new SelectList(_context.Course, "courseId", "title", enrollment.courseId);
            ViewData["studentId"] = new SelectList(_context.Student, "Id", "fullName", enrollment.studentId);
            return View(enrollment);
        }

        // GET: Enrollments/Edit/5
        [Authorize(Roles = "Admin")]
        public async Task<IActionResult> Edit(long? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var enrollment = await _context.Enrollment.FindAsync(id);
            if (enrollment == null)
            {
                return NotFound();
            }
            ViewData["courseId"] = new SelectList(_context.Course, "courseId", "title", enrollment.courseId);
            ViewData["studentId"] = new SelectList(_context.Student, "Id", "firstName", enrollment.studentId);
            return View(enrollment);
        }

        // POST: Enrollments/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        [Authorize(Roles = "Admin")]
        public async Task<IActionResult> Edit(long id, [Bind("enrollmentId,courseId,studentId,semester,year,grade,seminalUrl,projectUrl,examPoints,seminalPoints,projectPoints,additionalPoints,finishDate")] Enrollment enrollment)
        {
            if (id != enrollment.enrollmentId)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    _context.Update(enrollment);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!EnrollmentExists(enrollment.enrollmentId))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            ViewData["courseId"] = new SelectList(_context.Course, "courseId", "title", enrollment.courseId);
            ViewData["studentId"] = new SelectList(_context.Student, "Id", "firstName", enrollment.studentId);
            return View(enrollment);
        }

        // GET: Enrollments/Delete/5
        [Authorize(Roles = "Admin")]
        public async Task<IActionResult> Delete(long? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var enrollment = await _context.Enrollment
                .Include(e => e.course)
                .Include(e => e.student)
                .FirstOrDefaultAsync(m => m.enrollmentId == id);
            if (enrollment == null)
            {
                return NotFound();
            }

            return View(enrollment);
        }

        // POST: Enrollments/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        [Authorize(Roles = "Admin")]
        public async Task<IActionResult> DeleteConfirmed(long id)
        {
            var enrollment = await _context.Enrollment.FindAsync(id);
            _context.Enrollment.Remove(enrollment);
            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }

        private bool EnrollmentExists(long id)
        {
            return _context.Enrollment.Any(e => e.enrollmentId == id);
        }
        // GET: Enrollments/StudentsEnrolledAtCourse/5/MarijaStefanoska
        [Authorize(Roles = "Teacher, Admin")]
        public async Task<IActionResult> StudentsEnrolledAtCourse(int? id, string teacher, int year)
        {
            if (id == null)
            {
                return NotFound();
            }
            var course = await _context.Course
                .FirstOrDefaultAsync(m => m.courseId == id);

            string[] names = teacher.Split(" ");
            var teacherModel = await _context.Teacher.FirstOrDefaultAsync(m => m.firstName == names[0] && m.lastName == names[1]);
            var userLoggedInId = HttpContext.Session.GetString("UserLoggedIn");
            if (userLoggedInId != teacherModel.teacherId.ToString() && userLoggedInId != "Admin")
            {
                return Forbid();
            }
            ViewBag.teacher = teacher;
            ViewBag.course = course.title;
            var enrollment = _context.Enrollment.Where(x => x.courseId == id && (x.course.firstTeacherId == teacherModel.teacherId || x.course.secondTeacherId == teacherModel.teacherId))
            .Include(e => e.course)
            .Include(e => e.student);
            await _context.SaveChangesAsync();
            IQueryable<int?> yearsQuery = _context.Enrollment.OrderBy(m => m.year).Select(m => m.year).Distinct();
            IQueryable<Enrollment> enrollmentQuery = enrollment.AsQueryable();
            if (year != null && year != 0)
            {
                enrollmentQuery = enrollmentQuery.Where(x => x.year == year);
            }
            else
            {
                enrollmentQuery = enrollmentQuery.Where(x => x.year == yearsQuery.Max());
            }

            if (enrollment == null)
            {
                return NotFound();
            }

            EnrollmentFilter viewmodel = new EnrollmentFilter
            {
                enrollments = await enrollmentQuery.ToListAsync(),
                yearsList = new SelectList(await yearsQuery.ToListAsync())
            };

            return View(viewmodel);
        }

        //THIS IS FOR TEACHER ROLE
        // GET: Enrollments/EditAsTeacher/5
        [Authorize(Roles = "Teacher")]
        public async Task<IActionResult> EditAsTeacher(long? id, string teacher)
        {
            if (id == null)
            {
                return NotFound();
            }
            string[] names = teacher.Split(" ");
            var teacherModel = await _context.Teacher.FirstOrDefaultAsync(m => m.firstName == names[0] && m.lastName == names[1]);
            var userLoggedInId = HttpContext.Session.GetString("UserLoggedIn");
            if (userLoggedInId != teacherModel.teacherId.ToString())
            {
                return Forbid();
            }
            var enrollment = await _context.Enrollment.FindAsync(id);
            if (enrollment == null)
            {
                return NotFound();
            }
            ViewBag.teacher = teacher;
            ViewData["courseId"] = new SelectList(_context.Course, "courseId", "title", enrollment.courseId);
            ViewData["studentId"] = new SelectList(_context.Student, "Id", "firstName", enrollment.studentId);
            return View(enrollment);
        }

        //THIS IS FOR TEACHER ROLE
        // POST: Enrollments/EditAsTeacher/5

Views/Enrollments/Create.cshtml
@model School_Management_System_Application.Models.Enrollment

@{
    ViewData["Title"] = "Create";
}

<h1>Create</h1>

<h4>Enrollment</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Create">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <div class="form-group">
                <label asp-for="courseId" class="control-label">Course</label>
                <select asp-for="courseId" class ="form-control" asp-items="ViewBag.courseId"></select>
                <span asp-validation-for="courseId" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="studentId" class="control-label">Student</label>
                <select asp-for="studentId" class ="form-control" asp-items="ViewBag.studentId"></select>
                <span asp-validation-for="studentId" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="semester" class="control-label"></label>
                <input asp-for="semester" class="form-control" />
                <span asp-validation-for="semester" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="year" class="control-label"></label>
                <input asp-for="year" class="form-control" />
                <span asp-validation-for="year" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="grade" class="control-label"></label>
                <input asp-for="grade" class="form-control" />
                <span asp-validation-for="grade" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="seminalUrl" class="control-label"></label>
                <input asp-for="seminalUrl" class="form-control" />
                <span asp-validation-for="seminalUrl" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="projectUrl" class="control-label"></label>
                <input asp-for="projectUrl" class="form-control" />
                <span asp-validation-for="projectUrl" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="examPoints" class="control-label"></label>
                <input asp-for="examPoints" class="form-control" />
                <span asp-validation-for="examPoints" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="seminalPoints" class="control-label"></label>
                <input asp-for="seminalPoints" class="form-control" />
                <span asp-validation-for="seminalPoints" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="projectPoints" class="control-label"></label>
                <input asp-for="projectPoints" class="form-control" />
                <span asp-validation-for="projectPoints" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="additionalPoints" class="control-label"></label>
                <input asp-for="additionalPoints" class="form-control" />
                <span asp-validation-for="additionalPoints" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="finishDate" class="control-label"></label>
                <input asp-for="finishDate" class="form-control" />
                <span asp-validation-for="finishDate" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="submit" value="Create" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

<div>
    @*<a asp-action="Index">Back to List</a>*@
    <a href="javascript:void(0);" onclick="history.go(-1);">Go back</a>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

Views/Enrollments/Delete.cshtml
@model School_Management_System_Application.Models.Enrollment

@{
    ViewData["Title"] = "Delete";
}

<h1>Delete</h1>

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>Enrollment</h4>
    <hr />
    <dl class="row">
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.course)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.course.title)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.student)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.student.firstName)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.semester)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.semester)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.year)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.year)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.grade)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.grade)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.seminalUrl)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.seminalUrl)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.projectUrl)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.projectUrl)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.examPoints)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.examPoints)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.seminalPoints)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.seminalPoints)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.projectPoints)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.projectPoints)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.additionalPoints)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.additionalPoints)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.finishDate)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.finishDate)
        </dd>
    </dl>
    
    <form asp-action="Delete">
        <input type="hidden" asp-for="enrollmentId" />
        <input type="submit" value="Delete" class="btn btn-danger" /> |
        @*<a asp-action="Index">Back to List</a>*@
        <a href="javascript:void(0);" onclick="history.go(-1);">Go back</a>
    </form>
</div>

Views/Enrollments/Details.cshtml
@model School_Management_System_Application.Models.Enrollment

@{
    ViewData["Title"] = "Details";
}

<h1>Details</h1>

<div>
    <h4>Enrollment</h4>
    <hr />
    <dl class="row">
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.course)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.course.title)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.student)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.student.firstName)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.semester)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.semester)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.year)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.year)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.grade)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.grade)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.seminalUrl)
        </dt>
        <dd class = "col-sm-10">
            @if(@Model.projectUrl != null)
            {    
                <a href="@Model.projectUrl">Open project link</a>
            }
            else
            {
                <span>No link uploaded</span>
            }
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.projectUrl)
        </dt>
        <dd class = "col-sm-10">
            @if(@Model.seminalUrl != null)
            {    
                <a href="~/seminals/@Model.seminalUrl">Open seminal file</a>
            }
            else
            {
                <span>No file uploaded</span>
            }
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.examPoints)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.examPoints)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.seminalPoints)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.seminalPoints)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.projectPoints)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.projectPoints)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.additionalPoints)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.additionalPoints)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.finishDate)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.finishDate)
        </dd>
    </dl>
</div>
<div>
    @if (User.Identity.IsAuthenticated && User.IsInRole("Admin"))
    {
        <a asp-action="Edit" asp-route-id="@Model?.enrollmentId">Edit</a>
        @Html.Raw("|");
    }
    @*<a asp-action="Index">Back to List</a>*@
    <a href="javascript:void(0);" onclick="history.go(-1);">Go back</a>
</div>

Views/Enrollments/Index.cshtml
@model IEnumerable<School_Management_System_Application.Models.Enrollment>

@{
    ViewData["Title"] = "Index";
}

<h1>Enrollment</h1>

<p>
    <a asp-action="Create">Create New</a>
</p>
<table class="table">
    <thead>
        <tr>
            <th>
                @Html.DisplayNameFor(model => model.course)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.student)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.semester)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.year)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.grade)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.seminalUrl)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.projectUrl)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.examPoints)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.seminalPoints)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.projectPoints)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.additionalPoints)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.totalPoints)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.finishDate)
            </th>
            <th></th>
        </tr>
    </thead>
    <tbody>
@foreach (var item in Model) {
        <tr>
            <td>
                @Html.DisplayFor(modelItem => item.course.title)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.student.fullName)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.semester)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.year)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.grade)
            </td>
            <td>
                @if(@item.seminalUrl != null)
                {    
                        <a href="~/seminals/@item.seminalUrl">Open seminal file</a>
                    }
                    else
                    {
                        <span>No file uploaded</span>
                    }
            </td>
            <td>
                 @if(@item.projectUrl != null)
                {    
                        <a href="@item.projectUrl">Open project link</a>
                    }
                    else
                    {
                        <span>No link uploaded</span>
                    }
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.examPoints)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.seminalPoints)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.projectPoints)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.additionalPoints)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.totalPoints)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.finishDate)
            </td>
            <td>
                <a asp-action="Edit" asp-route-id="@item.enrollmentId">Edit</a> |
                <a asp-action="Details" asp-route-id="@item.enrollmentId">Details</a> 
                @if (User.Identity.IsAuthenticated && User.IsInRole("Admin"))
                 {
                     @Html.Raw("|");
                     <a asp-action="Delete" asp-route-id="@item.enrollmentId">Delete</a>
                 }
            </td>
        </tr>
}
    </tbody>
</table>
<a href="javascript:void(0);" onclick="history.go(-1);">Go back</a>

Views/Enrollments/StudentsEnrolledAtCourse.cshtml
@model School_Management_System_Application.ViewModels.EnrollmentFilter

@{
    ViewData["Title"] = "Index";
}

<h1>Enrolled students at "@ViewBag.course" from teacher "@ViewBag.teacher"</h1>

<form asp-controller="Enrollments" asp-action="StudentsEnrolledAtCourse" asp-route-teacher="@ViewBag.teacher">
    <p>
        Year: <select asp-for="year" asp-items="Model.yearsList">
            <option>Select year</option>
        </select>
        <input type="submit" value="Filter" />
    </p>
</form>

<table class="table">
    <thead>
        <tr>
            <th>
                @Html.DisplayNameFor(model => model.enrollments[0].course)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.enrollments[0].student)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.enrollments[0].semester)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.enrollments[0].year)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.enrollments[0].grade)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.enrollments[0].seminalUrl)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.enrollments[0].projectUrl)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.enrollments[0].examPoints)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.enrollments[0].seminalPoints)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.enrollments[0].projectPoints)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.enrollments[0].additionalPoints)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.enrollments[0].totalPoints)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.enrollments[0].finishDate)
            </th>
            <th></th>
        </tr>
    </thead>
    <tbody>
@foreach (var item in Model.enrollments) {
        <tr>
            <td>
                @Html.DisplayFor(modelItem => item.course.title)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.student.fullName)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.semester)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.year)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.grade)
            </td>
            <td>
                @if(@item.seminalUrl != null)
                {    
                        <a href="~/seminals/@item.seminalUrl">Open seminal file</a>
                    }
                    else
                    {
                        <span>No file uploaded</span>
                    }
            </td>
            <td>
                 @if(@item.projectUrl != null)
                {    
                        <a href="@item.projectUrl">Open project link</a>
                    }
                    else
                    {
                        <span>No link uploaded</span>
                    }
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.examPoints)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.seminalPoints)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.projectPoints)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.additionalPoints)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.totalPoints)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.finishDate)
            </td>
            <td>
                @if (item.finishDate == null)
                {
                    <a asp-action="EditAsTeacher" asp-route-id="@item.enrollmentId" asp-route-teacher="@ViewBag.teacher">Edit</a>
                    <span> |</span>
                }
                <a asp-action="Details" asp-route-id="@item.enrollmentId">Details</a> 
                 @if (User.Identity.IsAuthenticated && User.IsInRole("Admin"))
                 {
                     @Html.Raw("|");
                <a asp-action="Delete" asp-route-id="@item.enrollmentId">Delete</a>
                 }
            </td>
        </tr>
}
    </tbody>
</table>
<a href="javascript:void(0);" onclick="history.go(-1);">Go back</a>