Models/Teacher.cs
using School_Management_System_Application.Areas.Identity.Data;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace School_Management_System_Application.Models
{
    public class Teacher
    {
        public int teacherId { get; set; }
        [StringLength(50, MinimumLength = 3)]
        [Required]
        [Display(Name = "First Name")]
        public string firstName { get; set; }
        
        [StringLength(50, MinimumLength = 3)]
        [Required]
        [Display(Name = "Last Name")]
        public string lastName { get; set; }

        [StringLength(50, MinimumLength = 3)]
        [Display(Name = "Degree")]
        public string? degree { get; set; }

        [StringLength(25, MinimumLength = 3)]
        [Display(Name = "Academic Rank")]
        public string? academicRank {get; set;}

        [StringLength(10, MinimumLength = 2)]
        [Display(Name = "Office Number")]
        public string? officeNumber { get; set; }

        [Display(Name = "Hire Date")]
        [DataType(DataType.Date)]
        public DateTime? hireDate { get; set; }

        public string? profilePicture { get; set; }

        public string fullName
        {
            get
            {
                return string.Format("{0} {1}", firstName, lastName);
            }
        }

        public string? userIdentityId { get; set; }

        public User? userIdentity { get; set; }
    }
}

Controllers/TeachersController.cs
#nullable disable
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text.RegularExpressions;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using School_Management_System_Application.Areas.Identity.Data;
using School_Management_System_Application.Data;
using School_Management_System_Application.Models;
using School_Management_System_Application.ViewModels;

namespace School_Management_System_Application.Controllers
{
    public class TeachersController : Controller
    {
        private readonly School_Management_System_ApplicationContext _context;
        private UserManager<User> _userManager;

        public TeachersController(School_Management_System_ApplicationContext context, UserManager<User> userManager)
        {
            _context = context;
            _userManager = userManager;
        }

        // GET: Teachers
        [Authorize(Roles = "Admin")]
        public async Task<IActionResult> Index(string fullName, string academicrank, string degree)
        {

            IQueryable<Teacher> teachersQuery = _context.Teacher.AsQueryable();
            IQueryable<string> academicRanksQuery = _context.Teacher.OrderBy(m => m.academicRank).Select(m => m.academicRank).Distinct();
            IQueryable<string> degreesQuery = _context.Teacher.OrderBy(m => m.degree).Select(m => m.degree).Distinct();
            if (!string.IsNullOrEmpty(fullName))
            {
                if (fullName.Contains(" "))
                {
                    string[] names = fullName.Split(" ");
                    teachersQuery = teachersQuery.Where(x => x.firstName.Contains(names[0]) || x.lastName.Contains(names[1]) ||
                    x.firstName.Contains(names[1]) || x.lastName.Contains(names[0]));
                }
                else
                {
                    teachersQuery = teachersQuery.Where(x => x.firstName.Contains(fullName) || x.lastName.Contains(fullName));
                }
            }
            if (!string.IsNullOrEmpty(academicrank))
            {
                teachersQuery = teachersQuery.Where(x => x.academicRank.Contains(academicrank));
            }
            if (!string.IsNullOrEmpty(degree))
            {
                teachersQuery = teachersQuery.Where(x => x.degree.Contains(degree));
            }
            var TeacherFilterVM = new TeacherFilter
            {
                teachers = await teachersQuery.ToListAsync(),
                academicRanks = new SelectList(await academicRanksQuery.ToListAsync()),
                degrees = new SelectList(await degreesQuery.ToListAsync())
            };

            return View(TeacherFilterVM);
        }

        // GET: Teachers/Details/5
        [Authorize]
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var teacher = await _context.Teacher
                .FirstOrDefaultAsync(m => m.teacherId == id);
            if (teacher == null)
            {
                return NotFound();
            }

            EditPictureTeacher viewmodel = new EditPictureTeacher
            {
                teacher = teacher,
                profilePictureName = teacher.profilePicture
            };

            return View(viewmodel);
        }

        // GET: Teachers/Create
        [Authorize(Roles = "Admin")]
        public IActionResult Create()
        {
            return View();
        }

        // POST: Teachers/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        [Authorize(Roles = "Admin")]
        public async Task<IActionResult> Create([Bind("teacherId,firstName,lastName,degree,academicRank,officeNumber,hireDate")] Teacher teacher)
        {
            if (ModelState.IsValid)
            {

                var User = new User();
                User.Email = teacher.firstName.ToLower() + "." + teacher.lastName.ToLower() + "@school.com";
                User.UserName = teacher.firstName.ToLower() + "." + teacher.lastName.ToLower() + "@school.com";
                string userPWD = "Teacher123";
                IdentityResult chkUser = await _userManager.CreateAsync(User, userPWD);
                //Add default User to Role Admin
                if (chkUser.Succeeded) { var result1 = await _userManager.AddToRoleAsync(User, "Teacher"); }
                teacher.userIdentityId = User.Id;
                _context.Add(teacher);
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
            }
            return View(teacher);
        }

        // GET: Teachers/Edit/5
        [Authorize(Roles = "Admin")]
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var teacher = await _context.Teacher.FindAsync(id);
            if (teacher == null)
            {
                return NotFound();
            }
            return View(teacher);
        }

        // POST: Teachers/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        [Authorize(Roles = "Admin")]
        public async Task<IActionResult> Edit(int id, [Bind("teacherId,firstName,lastName,degree,academicRank,officeNumber,hireDate,profilePicture")] Teacher teacher)
        {
            if (id != teacher.teacherId)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    _context.Update(teacher);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!TeacherExists(teacher.teacherId))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            return View(teacher);
        }

        // GET: Teachers/Delete/5
        [Authorize(Roles = "Admin")]
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var teacher = await _context.Teacher
                .FirstOrDefaultAsync(m => m.teacherId == id);
            if (teacher == null)
            {
                return NotFound();
            }

            return View(teacher);
        }

        // POST: Teachers/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        [Authorize(Roles = "Admin")]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            var teacher = await _context.Teacher.FindAsync(id);
            IQueryable<Course> courses = _context.Course.AsQueryable();
            IQueryable<Course> courses1 = courses.Where(x => x.firstTeacherId == teacher.teacherId);
            IQueryable<Course> courses2 = courses.Where(x => x.secondTeacherId == teacher.teacherId);
            foreach (var course in courses1)
            {
                course.firstTeacherId = null;
            }
            foreach (var course in courses2)
            {
                course.secondTeacherId = null;
            }
            _context.Teacher.Remove(teacher);
            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));  
            }

        private bool TeacherExists(int id)
        {
            return _context.Teacher.Any(e => e.teacherId == id);
        }
        // GET: Teachers/EditPicture/5
        [Authorize(Roles = "Admin")]
        public async Task<IActionResult> EditPicture(long? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var teacher = _context.Teacher.Where(x => x.teacherId == id).First();
            if (teacher == null)
            {
                return NotFound();
            }

            EditPictureTeacher viewmodel = new EditPictureTeacher
            {
                teacher = teacher,
                profilePictureName = teacher.profilePicture
            };

            return View(viewmodel);
        }

        // POST: Teachers/EditPicture/5
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        [Authorize(Roles = "Admin")]
        public async Task<IActionResult> EditPicture(long id, EditPictureTeacher viewmodel)
        {
            if (id != viewmodel.teacher.teacherId)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    if (viewmodel.profilePictureFile != null)
                    {
                        string uniqueFileName = UploadedFile(viewmodel);
                        viewmodel.teacher.profilePicture = uniqueFileName;
                    }
                    else
                    {
                        viewmodel.teacher.profilePicture = viewmodel.profilePictureName;
                    }

                    _context.Update(viewmodel.teacher);

Views/Teachers/CoursesTeaching.cshtml
@model School_Management_System_Application.Models.Teacher

@{
    ViewData["Title"] = "Details";
}

<h1>Details of teacher</h1>

<div>
    <h4>Teacher</h4>
    <hr />
    <dl class="row">
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.firstName)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.firstName)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.lastName)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.lastName)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.degree)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.degree)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.academicRank)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.academicRank)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.officeNumber)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.officeNumber)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.hireDate)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.hireDate)
        </dd>
    </dl>
</div>
<div>
    <a asp-action="Edit" asp-route-id="@Model?.teacherId">Edit</a> |
    @*<a asp-action="Index">Back to List</a>*@
    <a href="javascript:void(0);" onclick="history.go(-1);">Go back</a>
</div>

Views/Teachers/Create.cshtml
@model School_Management_System_Application.Models.Teacher

@{
    ViewData["Title"] = "Create";
}

<h1>Create teacher</h1>

<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Create">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <div class="form-group">
                <label asp-for="firstName" class="control-label"></label>
                <input asp-for="firstName" class="form-control" />
                <span asp-validation-for="firstName" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="lastName" class="control-label"></label>
                <input asp-for="lastName" class="form-control" />
                <span asp-validation-for="lastName" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="degree" class="control-label"></label>
                <input asp-for="degree" class="form-control" />
                <span asp-validation-for="degree" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="academicRank" class="control-label"></label>
                <input asp-for="academicRank" class="form-control" />
                <span asp-validation-for="academicRank" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="officeNumber" class="control-label"></label>
                <input asp-for="officeNumber" class="form-control" />
                <span asp-validation-for="officeNumber" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="hireDate" class="control-label"></label>
                <input asp-for="hireDate" class="form-control" />
                <span asp-validation-for="hireDate" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="submit" value="Create" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

<div>
    @*<a asp-action="Index">Back to List</a>*@
    <a href="javascript:void(0);" onclick="history.go(-1);">Go back</a>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

Views/Teachers/Delete.cshtml
@model School_Management_System_Application.Models.Teacher

@{
    ViewData["Title"] = "Delete";
}

<h1>Delete teacher</h1>

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>Teacher</h4>
    <hr />
    <dl class="row">
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.firstName)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.firstName)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.lastName)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.lastName)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.degree)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.degree)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.academicRank)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.academicRank)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.officeNumber)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.officeNumber)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.hireDate)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.hireDate)
        </dd>
    </dl>
    
    <form asp-action="Delete">
        <input type="hidden" asp-for="teacherId" />
        <input type="submit" value="Delete" class="btn btn-danger" /> |
        @*<a asp-action="Index">Back to List</a>*@
        <a href="javascript:void(0);" onclick="history.go(-1);">Go back</a>
    </form>
</div>

Views/Teachers/Details.cshtml
@model School_Management_System_Application.ViewModels.EditPictureTeacher

@{
    ViewData["Title"] = "Details";
}

<h1>Details of teacher</h1>

<div>
    <h4>Teacher</h4>
    <hr />
    <dl class="row">
        <dt class = "col-sm-2">
           Profile picture:
        </dt>
        <dd class = "col-sm-10">
            <img src="~/profilePictures/@Model.teacher.profilePicture"
                class="rounded-circle"
                height="40" width="40"
                asp-append-version="true" />
        </dd> 
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.teacher.firstName)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.teacher.firstName)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.teacher.lastName)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.teacher.lastName)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.teacher.degree)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.teacher.degree)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.teacher.academicRank)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.teacher.academicRank)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.teacher.officeNumber)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.teacher.officeNumber)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.teacher.hireDate)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.teacher.hireDate)
        </dd>
    </dl>
</div>
<div>
    @if (User.Identity.IsAuthenticated && User.IsInRole("Admin"))
    {            
        <a asp-action="EditPicture" asp-route-id="@Model?.teacher.teacherId">Edit picture</a> 
        @Html.Raw("|");
        <a asp-action="Edit" asp-route-id="@Model?.teacher.teacherId">Edit</a> 
        @Html.Raw("|");
        //<a asp-action="Index">Back to List</a>
        <a href="javascript:void(0);" onclick="history.go(-1);">Go back</a>
    }
</div>

Views/Teachers/Edit.cshtml
@model School_Management_System_Application.Models.Teacher

@{
    ViewData["Title"] = "Edit";
}

<h1>Edit teacher</h1>

<h4>Teacher</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Edit">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <input type="hidden" asp-for="teacherId" />
            <div class="form-group">
                <label asp-for="firstName" class="control-label"></label>
                <input asp-for="firstName" class="form-control" />
                <span asp-validation-for="firstName" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="lastName" class="control-label"></label>
                <input asp-for="lastName" class="form-control" />
                <span asp-validation-for="lastName" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="degree" class="control-label"></label>
                <input asp-for="degree" class="form-control" />
                <span asp-validation-for="degree" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="academicRank" class="control-label"></label>
                <input asp-for="academicRank" class="form-control" />
                <span asp-validation-for="academicRank" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="officeNumber" class="control-label"></label>
                <input asp-for="officeNumber" class="form-control" />
                <span asp-validation-for="officeNumber" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="hireDate" class="control-label"></label>
                <input asp-for="hireDate" class="form-control" />
                <span asp-validation-for="hireDate" class="text-danger"></span>
            </div>
            <div class="form-group" style="display:none">
                <label asp-for="profilePicture" class="control-label"></label>
                <input asp-for="profilePicture" class="form-control" readonly="@(true)">
                <span asp-validation-for="profilePicture" class="text-danger"></span>
            </div>
            <div class="form-group" style="display:none">
                <label asp-for="userIdentityId" class="control-label"></label>
                <input asp-for="userIdentityId" class="form-control" readonly="@(true)">
                <span asp-validation-for="userIdentityId" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="submit" value="Save" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

<div>
    @*<a asp-action="Index">Back to List</a>*@
    <a href="javascript:void(0);" onclick="history.go(-1);">Go back</a>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

Views/Teachers/EditPicture.cshtml
@model School_Management_System_Application.ViewModels.EditPictureTeacher

@{
    ViewData["Title"] = "EditPicture";
}

<h1>Edit teacher</h1>

<h4>Teacher</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="EditPicture" enctype="multipart/form-data">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <input type="hidden" asp-for="teacher.teacherId" />
            <div class="form-group" style="display:none">
                <label asp-for="teacher.firstName" class="control-label"></label>
                <input asp-for="teacher.firstName" class="form-control" />
                <span asp-validation-for="teacher.firstName" class="text-danger"></span>
            </div>
            <div class="form-group" style="display:none">
                <label asp-for="teacher.lastName" class="control-label"></label>
                <input asp-for="teacher.lastName" class="form-control" />
                <span asp-validation-for="teacher.lastName" class="text-danger"></span>
            </div>
            <div class="form-group" style="display:none">
                <label asp-for="teacher.degree" class="control-label"></label>
                <input asp-for="teacher.degree" class="form-control" />
                <span asp-validation-for="teacher.degree" class="text-danger"></span>
            </div>
            <div class="form-group" style="display:none">
                <label asp-for="teacher.academicRank" class="control-label"></label>
                <input asp-for="teacher.academicRank" class="form-control" />
                <span asp-validation-for="teacher.academicRank" class="text-danger"></span>
            </div>
            <div class="form-group" style="display:none">
                <label asp-for="teacher.officeNumber" class="control-label"></label>
                <input asp-for="teacher.officeNumber" class="form-control" />
                <span asp-validation-for="teacher.officeNumber" class="text-danger"></span>
            </div>
            <div class="form-group" style="display:none">
                <label asp-for="teacher.hireDate" class="control-label"></label>
                <input asp-for="teacher.hireDate" class="form-control" />
                <span asp-validation-for="teacher.hireDate" class="text-danger"></span>
            </div>
             <div class="form-group" style="display:none">
                <label asp-for="teacher.profilePicture" class="control-label"></label>
                <input asp-for="profilePictureName" class="form-control" readonly="@(true)">
                <span asp-validation-for="teacher.profilePicture" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="profilePictureFile" class="control-label"></label>
                <div class="custom-file">
                    <input asp-for="profilePictureFile" class="custom-file-input" id="customFile">
                    <label class="custom-file-label" for="customFile"></label>
                </div>
            <div class="form-group">
                <input type="submit" value="Save" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

<div>
    @*<a asp-action="Details">Back to Details</a>*@
    <a href="javascript:void(0);" onclick="history.go(-1);">Go back</a>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

Views/Teachers/Index.cshtml
@model School_Management_System_Application.ViewModels.TeacherFilter

@{
    ViewData["Title"] = "Index";
}

<h1>Teachers</h1>

<p>
    <a asp-action="Create">Create New</a>
</p>

<form asp-controller="Teachers" asp-action="Index" method="get">
    <p>
        First or last name: <input type="text" asp-for="fullName" />
        Academic rank:
        <select asp-for="academicRank" asp-items="Model.academicRanks">
            <option value="">All</option>
        </select>
        Degree:
        <select asp-for="degree" asp-items="Model.degrees">
            <option value="">All</option>
        </select>
        <input type="submit" value="Filter" />
    </p>
</form>

<table class="table">
    <thead>
        <tr>
            <th>
                @Html.DisplayNameFor(model => model.teachers[0].firstName)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.teachers[0].lastName)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.teachers[0].degree)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.teachers[0].academicRank)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.teachers[0].officeNumber)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.teachers[0].hireDate)
            </th>
            <th>
                Courses
            </th>
            <th></th>
        </tr>
    </thead>
    <tbody>
@foreach (var item in Model.teachers) {
        <tr>
            <td>
                @Html.DisplayFor(modelItem => item.firstName)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.lastName)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.degree)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.academicRank)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.officeNumber)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.hireDate)
            </td>
            <td>
                <a asp-controller="Courses" asp-action="CoursesTeaching" asp-route-id="@item.teacherId">
                    Check the courses this teacher is teaching
                </a>
            </td>
            <td>
                <a asp-action="Edit" asp-route-id="@item.teacherId">Edit</a> |
                <a asp-action="Details" asp-route-id="@item.teacherId">Details</a> |
                <a asp-action="Delete" asp-route-id="@item.teacherId">Delete</a>
            </td>
        </tr>
}
    </tbody>
</table>
<a href="javascript:void(0);" onclick="history.go(-1);">Go back</a>